[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[[bin]]
name = "zero2prod"
path = "src/main.rs"


[dependencies]
actix-web = "4.0.0-beta.18"
actix-http="3.0.0-beta.17"
reqwest = "0.11.8"
actix-rt = "2.5.0"
tokio = { version = "1.15.0", features = ["full"] }
serde = { version = "1.0.132", features = ["derive"] }
