[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[[bin]]
name = "zero2prod"
path = "src/main.rs"


[dependencies]
actix-web = "4.0.0-beta.18"
actix-http="3.0.0-beta.17"
actix-rt = "2.5.0"
tokio = { version = "1.15.0", features = ["full"] }
serde = { version = "1.0.132", features = ["derive"] }
config = "0.11.0"
uuid = { version = "0.8.2", features = ["v4"] }
chrono = "0.4.19"
tracing = { version = "0.1.29", features = ["log"] }
tracing-futures = "0.2.5"
tracing-subscriber = { version = "0.3.5", features = ["registry" ,"env-filter"] }
tracing-bunyan-formatter = "0.3.1"
tracing-log = "0.1.2"
tracing-actix-web = "0.5.0-beta.3"


[dependencies.sqlx]
version = "0.5.10"
default-features = false
features = [
    "postgres",
    "runtime-actix-rustls",
    "macros",
    "uuid",
    "chrono",
    "migrate"
]

[dev-dependencies]
once_cell = "1.9.0"
reqwest = "0.11.8"
